### ISSUE TITLE
容易误删的危险 希望能区别嵌入块与引用块

### ISSUE THREAD

**Issue by babygaogao** [logseq/db-test-cn#28]
### Search first

- [x]  I searched and no similar issues were found

### What Happened?
嵌入块与引用块的呈现方式逻辑不清晰
这是目前的logseq，希望嵌入块与引用块能用node虚线小圆点区别，建议node节点虚线小圆点要比句子长方框那种嵌入块更简洁，如果能带上几种tag自带的颜色更好分辨，此时，node reference 与 node embed 混淆
![image](https://github.com/user-attachments/assets/91dab659-6875-4348-94a3-2a6a63bd1f22)

### Expected Behavior

一、希望引用块能智能改进一些，参考案例，这是一个带其他文字的 行内引用块 智能的行内引用块的实例长句子，不需要区分引用块还是嵌入块的范例 ，这样引用的方式是下划线，文字颜色跟随引用块元地址的标签色很好辨认，按shift 点击 展开编辑
二、希望引用块 也就是 node reference 能够跟随彩色标签的颜色，好区别
三、希望 嵌入块 也就是 node embed 这种高度危险会误删的模块，不只是在节点bullet用虚线与标签颜色标明，在编辑与删除时，激活一个方框作为分身影子 的警示
![image](https://github.com/user-attachments/assets/ec4c4827-d615-4c03-8b14-f91685089e89)
编辑状态的 node embed 嵌入块
![image](https://github.com/user-attachments/assets/af439272-5995-46fb-a9bb-99a8e1444a89)

### Browser, Desktop or Mobile Platform Information
No response

### Additional Context
No response

### Are you willing to submit a PR? If you know how to fix the bug.
 - [ ] I'm willing to submit a PR (Thank you!)

```[tasklist]
### Tasks
- [ ] node embed 嵌入块的节点虚线圈与颜色跟随标签
- [ ] node embed 嵌入块危险删除的编辑框提示
- [ ] node reference 引用块的跟随原所在block的标签变色
```

**Comment by xiang578** [comment]
tana 的方是确实看起来更明显一些。
